### ISSUE TITLE
Situació al menú de navegació

### ISSUE THREAD

**Issue by projeccions-eulalia** [pdc-frans/pdc-hub-tracker#20]
Quan, per exemple, estas treballant dins d'una categoria, per anar als diferents metadocuments de la mateixa, el menú de l'esquerra torna al menú principal. Es podria quedar a la categoria on s'està treballant?

**Comment by pdc-andrea** [comment]
Grande!!! Molaria mooooolt

El dijous, 2 de juliol de 2015, projeccions-eulalia <
notifications@github.com> va escriure:

> Quan, per exemple, estas treballant dins d'una categoria, per anar als
> diferents metadocuments de la mateixa, el menú de l'esquerra torna al menú
> principal. Es podria quedar a la categoria on s'està treballant?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pdc-frans/pdc-hub-tracker/issues/20>.
>


-- 
Andrea Obach
Projeccions PDC
Carrer Montserrat, 45
08340 Vilassar de Mar
Barcelona
T. +34 616 388 934
M. +34 937595668

**Comment by pdc-frans** [comment]
Implementat commit del 24 de Juliol
