### ISSUE TITLE
accents en el nom de metadocuments

### ISSUE THREAD

**Issue by projeccions-eulalia** [pdc-frans/pdc-hub-tracker#32]
Quan creem un metadoc amb lletra accentuada (í), no surt bé. Si ho canviem editant el nom des de l'editor (a dalt a la dreta) clicant el nom del metadoc i corregint-lo, segueix sortint malament. Només es pot canviar mitjançant /metadocument, llavors sí q es corregeix.

**Comment by pdc-frans** [comment]
Està repetit, mira el #3 
Tel tanco eh!
 :^*
