### ISSUE TITLE
Adaptabilitat a pantalles petites

### ISSUE THREAD

**Issue by pdc-roger** [pdc-frans/pdc-hub-tracker#35]
Quan es visualitza el Backend en pantalles de mida petita, i els botons del menu superior(Publish content i despres content management) i/o els botons de la barra esquerra vertical (+Category, +Metadocument) si no hi caben, enlloc de fer resize, desapareixen.

Els scrolls només afecten al cos de la pàgina pero no als menús.

![cap](https://cloud.githubusercontent.com/assets/13136026/10303715/ebcebbbc-6c15-11e5-9226-dac6fc9b8fcb.png)

**Comment by pdc-frans** [comment]
Parcialment adaptat, excepte el menú superior que demana un mínim d'amplada (forçat a CSS i fa aparèixer scroll)
